server:
  port: 9400
  tomcat:
    max-threads: 5000
    max-connections: 20000
    accept-count: 2000
    min-spare-threads: 2000
    connection-timeout: 60000
    max-http-header-size: 655360
    max-http-post-size: -1
    uri-encoding: UTF-8

  servlet:
    context-path: /

spring:
  application:
    name: retask4j-http-server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  mvc:
    static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/static
  config:
    import: classpath:config.yml

logging:
  config: classpath:log4j2.xml

